### ISSUE TITLE
grid.as                  getCellAppearance           56 Исключение AngelScript. - 8.3.18.1363

### ISSUE THREAD

**Issue by Wdivin** [infostart-hub/snegopat_modul#10]
23.07.2021 13:45:18 |!!!| grid.as                  getCellAppearance           56 Исключение AngelScript.
                    |  .|     Процесс: 1cv8.exe ( 8.03.0018.1363 )
                    |  .|     Core.As: 1.0.0.9
                    |  .|      Модуль: Snegopat (  ) 
                    |  .|        Файл: E:\Soft\Snegopat-new\modules\Snegopat\engine\grid.as
                    |  .|      Строка: 56
                    |  .|     Функция: ICellAppearance@ IDataRow::getCellAppearance(int)
                    |  .|      Строка: 56
                    |  .|    Описание: Исключение 0xC0000005 по адресу 0x04364A10 ( frame.dll ) при вызове функции "IGridUISource::getCellFormat"
                    |  .|              Стек вызовов:
                    |  .|                (null) : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), строка 0,0
                    |  .|                E:\Soft\Snegopat-new\modules\Snegopat\engine\com_designer.as : void TimerHandler::handler(uint64), строка 433,9
                    |  .|              This object at 0x60B55B60:
                    |  .|                _owner = script object 'IDataSource' (0x61D344E0)
                    |  .|                bkmk = native object 'IV8Bookmark' (0x61D6AFC0)
                    |  .|              Переменные:
                    |  .|                columnID = 0
                    |  .|                pCA = script object 'ICellAppearance' (0x617E5D70)

**Comment by Wdivin** [comment]
х64

**Comment by artbear** [comment]
Сложно решать такой ишуз,
не описано, какие действия приводят к падению (
значит, сложно повторить

подозреваю, что этот ишуз не будет решен или решен в рамках других проблем
