### ISSUE TITLE
Исключение 0xC0000005 по адресу 0x8F3F6290 ( core_as.dll ) при вызове функции "set_int_ptr" - 8.3.17.1851

### ISSUE THREAD

**Issue by missery0** [infostart-hub/snegopat_modul#17]
29.07.2021 09:33:46 |!!!| stlstd.v__global         v8malloc                    11 Исключение AngelScript.
                    |  .|     Процесс: 1cv8.exe ( 8.03.0017.1851 )
                    |  .|     Core.As: 1.0.0.9
                    |  .|      Модуль: Snegopat (  ) 
                    |  .|        Файл: C:\Users\user\Desktop\Снегопат\modules\Snegopat\v8api\stlstd.v__global
                    |  .|      Строка: 11
                    |  .|     Функция: uint64 v8malloc(uint64)
                    |  .|      Строка: 11
                    |  .|    Описание: Исключение 0xC0000005 по адресу 0x8F3F6290 ( core_as.dll ) при вызове функции "set_int_ptr"
                    |  .|              Стек вызовов:
                    |  .|                C:\Users\user\Desktop\Снегопат\modules\Snegopat\v8api\string.v__v8string : void v8string__ctor3(v8string&inout, uint64, uint64), строка 34,4
                    |  .|                C:\Users\user\Desktop\Снегопат\modules\Snegopat\v8api\string.v__v8string : void v8string__opAssign(v8string&inout, const string&in), строка 101,3
                    |  .|              Переменные:
                    |  .|                count = 0x000000000000186A
                    |  .|                m = 0x0000000110BDD020
                    |  .|                km = 0x10BDD040
29.07.2021 09:33:46 |!!!| stlstd.v__global         v8malloc                    12 Bad AngelScript result code in entranceToGateToAngelScript
29.07.2021 09:33:46 |!!!| StockListInterceptor.as  splitToLexemsTrap          116 Исключение AngelScript.
                    |  .|     Процесс: 1cv8.exe ( 8.03.0017.1851 )
                    |  .|     Core.As: 1.0.0.9
                    |  .|      Модуль: Snegopat (  ) 
                    |  .|        Файл: C:\Users\user\Desktop\Снегопат\modules\Snegopat\engine\StockListInterceptor.as
                    |  .|      Строка: 116
                    |  .|     Функция: void splitToLexemsTrap(ISourceLexer&inout, const v8string&inout, Vector&inout)
                    |  .|      Строка: 116
                    |  .|    Описание: Исключение 0xC0000005 по адресу 0x8F4504F8 ( core_as.dll ) при вызове функции "ISourceLexer::splitToLexems"
                    |  .|              Стек вызовов:
                    |  .|                 : void ITextExtColors_getColorsTrap_orig0(ITextExtColors&inout, const v8string&inout, Vector&inout), строка 0,0
                    |  .|                C:\Users\user\Desktop\Снегопат\modules\Snegopat\engine\sqlcolors.as : void ITextExtColors_getColorsTrap(ITextExtColors&inout, const v8string&inout, Vector&inout), строка 180,5
                    |  .|              Переменные:
                    |  .|                pThis = native object 'ISourceLexer' (0x05E1C1D0)
                    |  .|                source = native object 'v8string' (0x0014C050)
                    |  .|                lexems = native object 'Vector' (0x0014B628)
                    |  .|                newSource = native object 'v8string' (0x02DB3044)
29.07.2021 09:33:46 |!!!| StockListInterceptor.as  splitToLexemsTrap          117 Bad AngelScript result code in entranceToGateToAngelScript
29.07.2021 09:33:46 |!!!| string.v__v8string       v8string__dtor              48 Исключение AngelScript.
                    |  .|     Процесс: 1cv8.exe ( 8.03.0017.1851 )
                    |  .|     Core.As: 1.0.0.9
                    |  .|      Модуль: Snegopat (  ) 
                    |  .|        Файл: C:\Users\user\Desktop\Снегопат\modules\Snegopat\v8api\string.v__v8string
                    |  .|      Строка: 48
                    |  .|     Функция: void v8string__dtor(v8string&inout)
                    |  .|      Строка: 48
                    |  .|    Описание: Исключение 0xC0000005 по адресу 0x8F3F6270 ( core_as.dll ) при вызове функции "get_dword"
                    |  .|              Переменные:
                    |  .|                obj = native object 'v8string' (0x02DB3044)
29.07.2021 09:33:46 |!!!| StockListInterceptor.as  splitToLexemsTrap          117 Bad AngelScript result code in entranceToGateToAngelScript

**Comment by missery0** [comment]
1С:Предприятие 8.3 (8.3.17.1851)

**Comment by artbear** [comment]
Сложно решать такой ишуз,
не описано, какие действия приводят к падению (
значит, сложно повторить

подозреваю, что этот ишуз не будет решен или решен в рамках других проблем

**Comment by missery0** [comment]
> Сложно решать такой ишуз,
> не описано, какие действия приводят к падению (
> значит, сложно повторить
> 
> подозреваю, что этот ишуз не будет решен или решен в рамках других проблем

**Comment by missery0** [comment]
Ну я сам не знаю какие действия. Потому что для меня это тоже загадка. В общих чертах, я просто набираю текст кода и на этом все. После чего происходит вылет.
