### ISSUE TITLE
Падает при старте на Windows 2008 R2

### ISSUE THREAD

**Issue by ShootNICK-tm** [infostart-hub/snegopat_modul#19]
Имя сбойного приложения: starter.exe, версия: 1.0.0.9, отметка времени: 0x60ddcfb4
Имя сбойного модуля: KERNELBASE.dll, версия: 6.1.7601.24545, отметка времени 0x5e0eb7f5
Код исключения: 0xc0000005
Смещение ошибки: 0x0000df15
Идентификатор сбойного процесса: 0x1ad0
Время запуска сбойного приложения: 0x01d789a6b546b2c4
Путь сбойного приложения: D:\1_SnegoPat_3\starter.exe
Путь сбойного модуля: C:\Windows\syswow64\KERNELBASE.dll
Код отчета: f2f59f04-f599-11eb-838d-50e5493fdf51

**Comment by 7OH** [comment]
У клиентов на windows server 2008 R2 такое же.

**Comment by 7OH** [comment]
На 2008 сервере падает.
Добавили в исключения - не помогло.

**Comment by ShootNICK-tm** [comment]
да. 2008R2 был. Перешел на 2019 - зашебуршало.

**Comment by orefkov** [comment]
Устранено в core_loader.
