### ISSUE TITLE
[BUG] 8.3.10.2699 (x86)- Ошибка при старте конфигуратора. 

### ISSUE THREAD

**Issue by Saintinel** [infostart-hub/snegopat_modul#50]
Прикладываю лог
05.10.2021 15:10:06 |!!!| E:\Sneg\modules\Snegopat\engine\colorer.as (1782,5): warning: Compiling BreakPointDef@ ScintillaEditor::getBreakPointAtLine(int)
05.10.2021 15:10:06 |!!!| E:\Sneg\modules\Snegopat\engine\colorer.as (1784,16): error: Can't find unambiguous implicit conversion to make both expressions have the same type
05.10.2021 15:10:06 |!!!| Не удалось скомпилировать модуль Snegopat
05.10.2021 15:10:07 |!!!| При запуске Снегопата не найдена функция run

Ошибка воспроизводиться на 2х компьютерах.
При запуске с платформой 8.3.18.1208  на том же компъютере, ошибка не возникает

**Comment by orefkov** [comment]
Поправил в репо, в завтрашней сборке будет  и в дистрибе.
