### ISSUE TITLE
Не сохраняются примененные настройки горячих клавиш после аварийного завершения конфигуратора

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat_modul#6]
Не сохраняются примененные настройки горячих клавиш после аварийного завершения конфигуратора.

Порядок воспроизведения:

1. Открываю конфигуратор с новым Снегопатом х64, Снегопат успешно подключается.
2. Открываю главное окно Снегопата (`Ctrl + Shift + M`), перехожу на страницу `Хоткеи`
3. Нажимаю кнопку `Добавить`, указываю макрос `Навигатор по метаданным::Открыть объект метаданных` и комбинацию клавиш `Ctrl + ~`
4. Нажимаю `Применить`
5. Работаю в конфигураторе, внезапно конфигуратор падает (без сообщения об ошибки). Или, например, аналогично происходит, если его вырубить принудительно из диспетчера задач.
6. Закрываю конфигуратор повторно и снова открываю список хоткеев (п. 2)

В результате вижу, что в списке хоткеев назначенного мной на шаге 3 хоткея больше нет.

Core.As 1.0.0.8 + модуль Снегопат Альфа 6, собранный из актуальной версии репо (коммит https://github.com/infostart-hub/snegopat_modul/commit/fb7a3cc4ae7e2d4a134c4610df13bd5e13536022)

**Comment by orefkov** [comment]
Добавил сохранение профайла при изменении хоткеев.
