### ISSUE TITLE
Ctrl+1 в x64 вызывает падение конфигуратора

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat_modul#7]
Порядок воспроизведения:

1. Запускаю конфигуратор
2. Открываю любой модуль
3. Нажимаю `Ctrl+1` (список процедур и функций)

В результате конфигуратор аварийно завершает работу.

В x86 такая проблема не воспроизводится, список процедур и функций открывается и падения не происходит.
Аналогичная проблема была описана в чате https://t.me/snegopat_chat/9242

Дампы, полученные с ключем `-coreas-tracefunctions 1` прилагаю.

[8.03.0018.1483.zip](https://github.com/infostart-hub/snegopat_modul/files/6701331/8.03.0018.1483.zip)

Текущая версия: 1.0.0.8 ( 04.05.2021 01:38 )
Каталог: E:\akuntashov\SnegopatNew\core-as-1-0-08\modules\Snegopat\
Версия 1С: 8.3.18.1483

**Comment by orefkov** [comment]
Проблему подтверждаю, решение ищу.
