### ISSUE TITLE
Исключение 0xC0000005 по адресу 0xC27F1052 ( core_as.dll ) при вызове функции "QueryInterface" - 8.3.18.1363

### ISSUE THREAD

**Issue by Wdivin** [infostart-hub/snegopat_modul#9]
[2021-07-23-13-30-44.log.txt](https://github.com/infostart-hub/snegopat_modul/files/6868149/2021-07-23-13-30-44.log.txt)

х64

**Comment by Wdivin** [comment]
23.07.2021 13:30:44 |!!!| com_windows.as           getMdObjFromView           211 Исключение AngelScript.
                    |  .|     Процесс: 1cv8.exe ( 8.03.0018.1363 )
                    |  .|     Core.As: 1.0.0.9
                    |  .|      Модуль: Snegopat (  ) 
                    |  .|        Файл: E:\Soft\Snegopat-new\modules\Snegopat\engine\com_windows.as
                    |  .|      Строка: 211
                    |  .|     Функция: IMDObject@ getMdObjFromView(IFramedView@)
                    |  .|      Строка: 211
                    |  .|    Описание: Исключение 0xC0000005 по адресу 0xC27F1052 ( core_as.dll ) при вызове функции "QueryInterface"
                    |  .|              Стек вызовов:
                    |  .|                E:\Soft\Snegopat-new\modules\Snegopat\engine\com_windows.as : IV8MDObject@ IV8View::get_mdObj(), строка 544,13
                    |  .|                E:\Soft\Snegopat-new\modules\Snegopat\engine\com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), строка 0,13
                    |  .|              Переменные:
                    |  .|                view = native object 'IFramedView' (0x56BD0550)
                    |  .|                dv = native object 'IDocumentView' (0x00000000)
                    |  .|                doc = native object 'IDocument' (0x00000000)
                    |  .|                ui = native object 'IConfigMngrUI' (0x00000000)
                    |  .|                ow = native object 'IConfigMngrUIOwner' (0x00000000)
                    |  .|                pCont = native object 'IConnectionPointContainer' (0x00000000)
                    |  .|                pCP = native object 'IUnknown' (0x00000000)
                    |  .|                pdata = 0x0000000000000000
                    |  .|                size = 0x0300FC40
                    |  .|                i = 0x00000000
                    |  .|                pSink = native object 'DocSinkRef' (0x00000000)
                    |  .|                eh = native object 'IMDEditHelper' (0x00000000)
                    |  .|                er = native object 'IEventRecipient' (0x56BD04F0)
                    |  .|                ct = native object 'ICommandTarget' (0x595F1A08)
                    |  .|                obj = native object 'IMDObject' (0x00000000)
23.07.2021 13:31:02 |!!!| com_windows.as           getMdObjFromView           211 Исключение AngelScript.
                    |  .|     Процесс: 1cv8.exe ( 8.03.0018.1363 )
                    |  .|     Core.As: 1.0.0.9
                    |  .|      Модуль: Snegopat (  ) 
                    |  .|        Файл: E:\Soft\Snegopat-new\modules\Snegopat\engine\com_windows.as
                    |  .|      Строка: 211
                    |  .|     Функция: IMDObject@ getMdObjFromView(IFramedView@)
                    |  .|      Строка: 211
                    |  .|    Описание: Исключение 0xC0000005 по адресу 0xC27F1052 ( core_as.dll ) при вызове функции "QueryInterface"
                    |  .|              Стек вызовов:
                    |  .|                E:\Soft\Snegopat-new\modules\Snegopat\engine\com_windows.as : IV8MDObject@ IV8View::get_mdObj(), строка 544,13
                    |  .|                E:\Soft\Snegopat-new\modules\Snegopat\engine\com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), строка 0,13
                    |  .|              Переменные:
                    |  .|                view = native object 'IFramedView' (0x56BD0550)
                    |  .|                dv = native object 'IDocumentView' (0x00000000)
                    |  .|                doc = native object 'IDocument' (0x00000000)
                    |  .|                ui = native object 'IConfigMngrUI' (0x00000000)
                    |  .|                ow = native object 'IConfigMngrUIOwner' (0x00000000)
                    |  .|                pCont = native object 'IConnectionPointContainer' (0x00000000)
                    |  .|                pCP = native object 'IUnknown' (0x00000000)
                    |  .|                pdata = 0x0000000002AD6AEC
                    |  .|                size = 0x00000000
                    |  .|                i = 0x00000000
                    |  .|                pSink = native object 'DocSinkRef' (0x00000000)
                    |  .|                eh = native object 'IMDEditHelper' (0x00000000)
                    |  .|                er = native object 'IEventRecipient' (0x56BD04F0)
                    |  .|                ct = native object 'ICommandTarget' (0x595F1A08)
                    |  .|                obj = native object 'IMDObject' (0x00000000)

**Comment by artbear** [comment]
Сложно решать такой ишуз,
не описано, какие действия приводят к падению (
значит, сложно повторить

подозреваю, что этот ишуз не будет решен или решен в рамках других проблем
